---
- name: Deploy production version
  hosts: production_servers
  remote_user: david

  tasks:

  - name: Stop service
    community.docker.docker_compose:
      project_src: /srv/production/dm/tools/docker
      state: absent
      env_file: /srv/production/dm/tools/environments/production.env
    ignore_errors: yes

  - name: Deploy code
    ansible.builtin.git:
      repo: 'git@github.com:DlouhyDavid/DM.git'
      dest: /srv/production/dm
      version: "{{ GIT_BRANCH }}"
      force: true
  
  - name: Copy env
    command: "{{item}}"
    with_items:
      - cp "/srv/env/dm/production.env" "/srv/production/dm/tools/environments/production.env"

  - name: Start service
    community.docker.docker_compose:
      recreate: always
      project_name: dm_production
      project_src: /srv/production/dm/tools/docker
      env_file: /srv/production/dm/tools/environments/production.env