version: "3.9"
services:
  shiny:
      image: rocker/shiny:4.3.0
      ports:
        - "${DM_PORT}:3838"
      user: shiny
      volumes:
        - "${DM_LOCATION}/docker/shiny-server.conf:/etc/shiny-server/shiny-server.conf"
        - "${DM_LOCATION}:/srv/dm"
      restart: always
