version: "3.9"
services:
  server:
      image: rocker/tidyverse:4.1.3
      ports:
        - "${DM_PORT}:3838"
      volumes:
        - "${DM_LOCATION}:/srv/dm"
      restart: always
      command: R -e 'shiny::runApp("/srv/dm/web.R", port = 3838, host = "0.0.0.0")'
