version: "3.9"
services:
  server:
      image: rocker/tidyverse:4.1.3
      ports:
        - "${DM_PORT}:3838"
      volumes:
        - "${DM_LOCATION}:/srv/dm"
      restart: always
      entrypoint: ["/bin/bash", "/srv/dm/tools/docker/startup.sh"]
